- scripts/buildNeuron.sh
- scripts/install_debian.sh
- scripts/install_macOS.sh
- scripts/install_redhat.sh
- scripts/install_redhat_centos:8.sh
Upstream changes in NEURON caused `make docs` to execute several IPython
notebooks, which exposed two problems with the environment setup in this
repository.
- Upgrade pip before installing packages using it. Old pip did not
manage to resolve the required numpy version correctly on Debian.
- On RedHat systems NEURON installs files to both
${INSTALL_DIR}/lib/python and ${INSTALL_DIR}/lib64/python, but the
latter was not added to PYTHONPATH. Also avoid adding a trailing colon
if PYTHONPATH was empty.
The IPython notebook execution is quite slow and sometimes hits resource
limits in the GitHub Actions runners, so in fact we disable this by
replacing `make docs` with `make doxygen` and `make sphinx`.
> Fix CI builds after upstream documentation changes

- scripts/buildNeuron.sh
https://github.com/neuronsimulator/nrn/pull/962 added a dependency on `pytest-cov`.
@alexsavulescu @pramodk do you think we should integrate this repository into the main https://github.com/neuronsimulator/nrn one to help catch such issues earlier?
> Install pytest-cov

- scripts/install_redhat.sh
This fixes recent failures in the CentOS8 and Fedora 32 builds.
> Install diffutils on RedHat systems

- scripts/buildNeuron.sh
- scripts/install_debian.sh
- scripts/install_macOS.sh
- scripts/install_redhat.sh
- scripts/install_redhat_centos:8.sh
Ninja is faster (and better) than `make`, so this both makes the CI a little more efficient and is a (tiny) step towards encouraging people to use Ninja.
> Use Ninja instead of Unix Makefiles.

- scripts/install_debian.sh
https://github.com/neuronsimulator/nrn/issues/1045 tracks the issue that the `debian:stable` build in this repository is rather prone to hanging. This can happen in either the CTest suite or the wheel test.
So far this has not been reproduced locally, so it is not obvious how to solve it. This PR changes the Debian and Ubuntu builds to use MPICH instead of OpenMPI, to see if this has any impact on how often the jobs hang.
> Use MPICH instead of OpenMPI in some cases.

- .github/workflows/build-neuron.yml
Fedora 34 [was released](https://fedoramagazine.org/announcing-fedora-34), so we should bump our second-newest version from Fedora 32 to Fedora 33.
Also remove an (apparently harmless) duplicate `--create-home` option to `useradd`.
> Bump Fedora versions

- .github/workflows/build-neuron.yml
Closes #2 by enabling test builds of the latest release (currently v8.0.0).
At present these are only enabled:
```bash
if [ $(date +%u) -eq 1 ]
```
i.e. only on Mondays, which seemed like a reasonable compromise between wasting resources and missing issues that emerge.
> Test the latest NEURON release; only on Mondays.

- scripts/install_redhat.sh
This should fix the recent failures with `centos:8`, for example: https://github.com/neuronsimulator/nrn-build-ci/runs/2760370902?check_suite_focus=true
I filed a bug report upstream: https://bugs.centos.org/view.php?id=18212, but a workaround is just to add an extra `update` command, as suggested on that bug report.
> Update RedHat distributions before installing.

- .github/workflows/build-neuron.yml
Previously we just had Debian 10 via `debian:stable`, but it stopped working when Debian 11 was released.
This is now consistent with other distributions where we use the two newest releases.
Once the `debian:stable` image is working again we should change `debian:bullseye` to `debian:stable`.
> Update to build on Debian 10 and 11

- scripts/install_debian_debian:buster.sh
- scripts/install_debian_ubuntu:18.04.sh
At the time of writing, this provides 3.16.3 for `debian:buster` and 3.21.1 for `ubuntu:18.04`.
> Install newer CMake verisons for ubuntu:18.04 and debian:buster.

- .github/workflows/build-neuron.yml
- Update second-newest Fedora from 33 to 34.
- Do not test the latest NEURON release against Fedora 35 (https://github.com/neuronsimulator/nrn-build-ci/issues/28).
- NEURON `master` is still broken on Fedora 35 (https://github.com/neuronsimulator/nrn/issues/1525).
> Update Fedora jobs.

- .github/workflows/build-neuron.yml
Switch latest release testing to run on Thursday. Closes #28.
> NEURON 8.0.2 should be Fedora 35 compatible.

- .github/workflows/build-neuron.yml
- scripts/testNeuronWheel.sh
- wrappers/runUnprivileged.sh
The CI [failed this morning](https://github.com/neuronsimulator/nrn-build-ci/actions/runs/1960849855) and I realised that when we test the latest release (currently the 8.0.2 tag) of NEURON then we were still installing and testing `neuron-nightly` wheels.
With this change then the builds testing the `8.0.2` tag of NEURON install and test `neuron==8.0.2`.
> Test release wheels when testing tags.

- .github/workflows/build-neuron.yml
- scripts/buildNeuron.sh
- scripts/environment.sh
- scripts/install_debian.sh
- scripts/install_debian_ubuntu_18_04.sh
- scripts/install_redhat.sh
- scripts/install_redhat_centos_7.sh
- scripts/install_redhat_centos_stream8.sh
- scripts/testNeuronWheel.sh
- wrappers/runUnprivileged.sh
Support for Python 3.6 was dropped in neuronsimulator/nrn#1733. Now we:
- Install 3.8 on CentOS7 and CentOS Stream 8.
- Install 3.7 on Ubuntu 18.04.
- Drop a 3.6-specific workaround.
To get everything working, also:
- Install numpy using pip, not the package manager.
- Cleanup some old PATH/JUPYTER_PATH manipulation.
- Set up and use a virtual environment, as pythonX -m venv works on some
distributions when pythonX -m pip does not.
> Use Python 3.7+ everywhere.

- .github/workflows/build-neuron.yml
- scripts/install_debian.sh
- scripts/install_macOS.sh
- scripts/install_redhat.sh
This is an optional dependency in CoreNEURON.
Without it, some unit tests are not run.
Also, Fedora 36 is out so our 2nd-newest version should be 35.
> Install Boost, Fedora 34 -> 35

- .github/workflows/build-neuron.yml
Prepare for the `master` wheels to require GCC9+
Note that Debian Buster will still be used when the CI is launched against a specified NEURON branch.
Test-the-last-release day is Monday again (as the comment said).
> Exclude master + debian:buster

- .github/workflows/build-neuron.yml
- scripts/environment_redhat_centos_stream8.sh
- scripts/install_redhat.sh
- scripts/install_redhat_centos_7.sh
- scripts/install_redhat_centos_stream8.sh
* centos 7 has openmpi 1.10 version via `openmpi-devel` package
* when python is used to launch neuron, older openmpi versions
seem to have problem. See relevant discussion in
https://ngsolve.org/forum/ngspy-forum/771-open-mpi-question
* using newer openmpi (>=3) via `openmpi3-devel` package seems to
work fine
fixes neuronsimulator/nrn/issues/1968
> Use MPICH on centos 7 and use GCC v9 everywhere

- .github/workflows/build-neuron.yml
- https://github.com/BlueBrain/CoreNeuron/pull/862 cherry-picks the relevant fix into the 8.2 series branch
> Skip testing 8.2.1 on CentOS7

- .github/workflows/build-neuron.yml
- scripts/testNeuronWheel.sh
- wrappers/runUnprivileged.sh
- Avoid an old GitHub Action that used a deprecated NodeJS version.
- Improve logic for which wheels are tested: now the default branch of NEURON is tested with neuron-nightly, the latest release of NEURON is tested with the corresponding released wheel, and features branches of NEURON default to not testing wheels. All of the above are overriden if an Azure drop URL is given: in that case, the wheels from the drop are used.
> Avoid deprecations, improve wheel logic.

- .github/workflows/build-neuron.yml
- Test Fedora 36 and 37 instead of 35 and 36
- Don't test NEURON 8.2.1 against Fedora 37, as this ships with Python 3.11 and there are no wheels for that combination.
- Disable failing macOS builds; these also need fixes in `release/8.2` that will be included in 8.2.2
> Bump Fedora versions, skip Fedora 37 + NEURON 8.2.1, skip macOS + NEURON 8.2.1

- scripts/install_redhat_centos_7.sh
Around 17/12/2022 then the source RPM URL we use started redirecting.
> flex: follow redirects when downloading source RPM

- .github/workflows/build-neuron.yml
- README.md
- scripts/buildNeuron.sh
- scripts/environment_redhat_centos_stream9.sh
- scripts/install_debian_debian_buster.sh
> The current "stable" distribution of Debian is version 12, codenamed bookworm. It was released on June 10th, 2023. 
- OpenMPI workaround copied from https://github.com/neuronsimulator/nrn-build-ci/pull/59
> Debian {10,11} -> {11,12}; update docs

- .github/workflows/build-neuron.yml
- scripts/buildNeuron.sh
- scripts/install_macOS.sh
- Use `nrn_requirements.txt` and `ci_requirements.txt` to install the necessary python packages for the NEURON installation
- If `ci_requirements.txt` doesn't exist (NEURON 8.2.3) then just install the current packages listed in it
- Install the NMODL required packages from `external/nmodl/requirements.txt`
- Upgrade from MacOS 11,12 to 12, 13
- Install `setuptools` for `Python 12` support
- Recursively clone submodules
> Various CI fixes

- scripts/environment_redhat.sh
One of the init scripts in the latest version of LMOD doesn't handle `-e` mode properly, so as a fix we temporarily turn it off when using it.
> Fix for Fedora latest

- .github/workflows/build-neuron.yml
As per https://github.com/actions/runner-images/issues/10721, it will permanently be removed on 2024-12-03.
> Remove MacOS 12 from CI

- .github/workflows/build-neuron.yml
- scripts/environment_macOS.sh
- scripts/install_debian.sh
- scripts/install_redhat.sh
- scripts/install_redhat_almalinux_8_10.sh
- scripts/install_redhat_centos_stream9.sh
We removed Python 3.8 in https://github.com/neuronsimulator/nrn/pull/3108, so AlmaLinux and Ubuntu 20.04 started failing. To remedy this, on AlmaLinux we install 3.9 (available in default repos), and on Ubuntu we add another repo which has 3.9.
Also added better error handling (should now notify us if variables are missing or similar problems), and removed some unused env vars.
> Fixes for Python min and max versions

- .github/workflows/build-neuron-template.yml
- README.md
20.04 will reach EOL on 2025-05-31:
https://ubuntu.com/blog/ubuntu-20-04-eol-for-devicesional
> Bump Ubuntu from 20.04 to 22.04
